### ISSUE TITLE
Crash in certain setups, which can be made even with attached_node = 1

### ISSUE THREAD

**Issue by Calinou** [PilzAdam/carts#14]
The following screenshot shows a setup that makes the server “crash”, with no error message but only a timeout.

https://cdn.mediacru.sh/rtfXWAS0ioIE.jpg

**Comment by Kilarin** [comment]
this is happening in function cart:calc_rail_direction(pos, vel)
in the section:
   -- First try this HACK
   -- Move the cart on the rail if above or under it
The logic says: if the cart is stopped, check to see if there is a rail above or below me, and if there is, assume I've gotten off track and then recursively call cal_rail_direction from that other position.  In the configuration shown, this means that calc_rail_direction first realizes that it is not moving and there is a rail above it, and recursively calls calc_rail_direction for one node up, but THAT instance of calc_rail_direction realizes it is not moving and there is a rail below it, so it recursively calls calc_rail_direction on the node below it, and from there the recursion just keeps going deeper until the stack overflows I suppose.

When I get some more time I'll research exactly why this part of the code is needed, and see if I can fix it.  It should be as simple as checking first to see if the node you are on is a rail before doing any recursion, but I'd like to determine the REASON for this section of code, because there might be a simpler solution than recursion (such as just resetting the position).  I LOVE recursion, but I'm not certain it's necessary here.

**Comment by Kilarin** [comment]
Did a simple fix over lunch.  Solution is:
in function cart:calc_rail_direction(pos, vel)
change the following line from:
if cart_func.v3:equal(velocity, {x=0, y=0, z=0}) then  
to:
if cart_func.v3:equal(velocity, {x=0, y=0, z=0}) and not cart_func:is_rail(p) then

Now none of the recursive "Move the cart on the rail if above or under it" logic ever fires if the cart is currently ON a rail.  And even if the cart is not on the rail, the recursion ceases as soon as a rail is found.

The cart does reverse now, but I tested with the original code and apparently the cart always reverses if it hits a dead end rail that is a power rail.
